drop table IF EXISTS sensor;
CREATE TABLE sensor(id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, name varchar(30) NOT NULL check (char_length(name)>=2 and char_length(name)<=30), created_at timestamp without time zone, updated_at timestamp without time zone);
drop table IF EXISTS measure;
create table measure(id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, value float NOT NULL CHECK (value<=100 and value>=-100) , raining boolean DEFAULT FALSE, created_at timestamp without time zone, updated_at timestamp without time zone);